### ISSUE TITLE
src/usr.sbin/makefs/msdos/msdosfs_vfsops.c:410: return after free ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#103]
[src/usr.sbin/makefs/msdos/msdosfs_vfsops.c:410]: (error) Returning/dereferencing 'pmp' after it is deallocated / released

    if (pmp) {
        if (pmp->pm_inusemap)
            free(pmp->pm_inusemap);
        free(pmp);
    }
    errno = error;
    return pmp;

**Comment by dcvmoole** [comment]
Thank you. Same as for #102.
