### ISSUE TITLE
minix3 build error with latest master branch

### ISSUE THREAD

**Issue by SanchayanMaity** [Stichting-MINIX-Research-Foundation/minix#105]
I am following the documentation here
http://wiki.minix3.org/doku.php?id=developersguide:crosscompiling

and cross building for x86 to get a Qemu bootable image. Exact command I run is 
bash ./releasetools/x86_hdimage.sh 

I am running  Arch Linux which is fairly up to date with GCC 5.3.0 if that's relevant.

I keep running into the following build error and cannot get the latest master branch to build.

<snip>
#   compile  info/session.o
/home/sanchayan/GitSource/Minix/minix/../obj.i386/tooldir.Linux-4.1.16-1-lts-x86_64/bin/i586-elf32-minix-clang -O2   -std=gnu99    -Werror -Wno-format-security    --sysroot=/home/sanchayan/GitSource/Minix/minix/../obj.i386/destdir.i386 -I/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/info -I/home/sanchayan/GitSource/Minix/minix/../obj.i386/gnu/usr.bin/texinfo/common  -DDEFAULT_INFOPATH=\"/usr/pkg/info:/usr/X11R6/info:/usr/X11/info:/usr/local/info:/usr/share/info:/usr/info\" -I/home/sanchayan/GitSource/Minix/minix/gnu/usr.bin/texinfo/info/../common -I/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/lib  -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H  -c    /home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/info/session.c
/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/info/session.c:2023:20: error: taking the absolute value of unsigned type 'unsigned long' has no effect [-Werror,-Wabsolute-value]
      delta = MIN (labs (pos - (xref->start - strlen (INFO_XREF_LABEL))),
                   ^
/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/lib/system.h:291:20: note: expanded from macro 'MIN'
#define MIN(a,b) ((a) < (b) ? (a) : (b))
                   ^
/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/info/session.c:2023:20: note: remove the call to 'labs' since unsigned values cannot be negative
      delta = MIN (labs (pos - (xref->start - strlen (INFO_XREF_LABEL))),
                   ^~~~
/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/lib/system.h:291:20: note: expanded from macro 'MIN'
#define MIN(a,b) ((a) < (b) ? (a) : (b))
                   ^
/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/info/session.c:2023:20: error: taking the absolute value of unsigned type 'unsigned long' has no effect [-Werror,-Wabsolute-value]
      delta = MIN (labs (pos - (xref->start - strlen (INFO_XREF_LABEL))),
                   ^
/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/lib/system.h:291:32: note: expanded from macro 'MIN'
#define MIN(a,b) ((a) < (b) ? (a) : (b))
                               ^
/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/info/session.c:2023:20: note: remove the call to 'labs' since unsigned values cannot be negative
      delta = MIN (labs (pos - (xref->start - strlen (INFO_XREF_LABEL))),
                   ^~~~
/home/sanchayan/GitSource/Minix/minix/gnu/dist/texinfo/lib/system.h:291:32: note: expanded from macro 'MIN'
#define MIN(a,b) ((a) < (b) ? (a) : (b))
                               ^
2 errors generated.
*** [session.o] Error code 1

nbmake[9]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu/usr.bin/texinfo/info
1 error

nbmake[9]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu/usr.bin/texinfo/info
*** [dependall] Error code 2

nbmake[8]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu/usr.bin/texinfo/info
1 error

nbmake[8]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu/usr.bin/texinfo/info
*** [dependall-info] Error code 2

nbmake[7]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu/usr.bin/texinfo
1 error

nbmake[7]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu/usr.bin/texinfo
*** [dependall-texinfo] Error code 2

nbmake[6]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu/usr.bin
1 error

nbmake[6]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu/usr.bin
*** [dependall-usr.bin] Error code 2

nbmake[5]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu
1 error

nbmake[5]: stopped in /home/sanchayan/GitSource/Minix/minix/gnu
*** [dependall-gnu] Error code 2

nbmake[4]: stopped in /home/sanchayan/GitSource/Minix/minix
1 error

nbmake[4]: stopped in /home/sanchayan/GitSource/Minix/minix
*** [do-build] Error code 2

nbmake[3]: stopped in /home/sanchayan/GitSource/Minix/minix
1 error

nbmake[3]: stopped in /home/sanchayan/GitSource/Minix/minix
*** [build] Error code 2

nbmake[2]: stopped in /home/sanchayan/GitSource/Minix/minix
1 error

nbmake[2]: stopped in /home/sanchayan/GitSource/Minix/minix
*** [distribution] Error code 2

nbmake[1]: stopped in /home/sanchayan/GitSource/Minix/minix
1 error

nbmake[1]: stopped in /home/sanchayan/GitSource/Minix/minix
*** [release] Error code 2

nbmake: stopped in /home/sanchayan/GitSource/Minix/minix
1 error

nbmake: stopped in /home/sanchayan/GitSource/Minix/minix

ERROR: Failed to make release
*** BUILD ABORTED ***

I also tried doing a fresh build by deleting the build obj.i386 directory but no use. I can build an earlier 3.3.0 version of the git source tree in which the last commit is

commit 8933525b85c631b3d20bed940561520be2b81891
Author: Lionel Sambuc <lionel.sambuc@gmail.com>
Date:   Mon Oct 12 20:49:00 2015 +0200

    Fix default partition in clientctl.
    
    The partition numbering has changed with the new image creation
    framework.
    
    Change-Id: I0644e5879913bee067bc31376f81bc5407f4c81f

 minix/llvm/clientctl | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

**Comment by sambuc** [comment]
Thank you for the detailed report.

From what I see, I suspect GCC 5.x is a lot more pickier, or has new classes of warnings, compared to GCC 4.8 / 4.9.

As we compile as much as possible with `-Werror`, to transform warnings into errors, this causes issues when compiler start spilling out new warnings.

The tools we use are not the latest and greatest when it comes to binutils, gcc, and a few dependencies. Just keeping up to date with them would be a full-time job.

I'll look into either disabling the specific new warnings, or removing altogether the -Werror while building the `tools/`.

Meanwhile, you can try to `export WARNS=''; export NOGCCERRORS=yes` before starting your build. I can't test it right now, but the idea is to disable `-Werror` temporarily.

Regards,

Lionel

**Comment by SanchayanMaity** [comment]
Thanks for your reply.

I tried exporting with export WARNS=''; export NOGCCERRORS=yes from the command line and then invoking

bash ./releasetools/x86_hdimage.sh

but it does not remedy the situation.
