### ISSUE TITLE
Missing info about retrieving information about network setup

### ISSUE THREAD

**Issue by tps800** [Stichting-MINIX-Research-Foundation/minix#11]
The page "http://wiki.minix3.org/doku.php?id=usersguide:networkconfiguration" describes how to set up networking in minix rudimentary, but does not provide any information on how to retrieve information from an already set up network interface.

* Missing: hints on commands to retrieve interface setup
* Missing: hints on commands to retrieve routing setup

It is quite difficult to find information about "ifconfig" being available. Typing "route" just leads to "route: not found". Looking at the man-page to ifconfig doesn't give any further information on how to retrieve routing informations.

**Comment by Tookmund** [comment]
This information has now been added to the wiki.
To check your current IP address you can use ````hostaddr````

For future reference you should always check ````man -k```` when confused about what command to use. ````man -k```` is currently broken but can be fixed by applying #34

**Comment by Tookmund** [comment]
I think I have fixed this issue. Could someone close it please?

**Comment by sambuc** [comment]
Given all the above posts, I believe the issue has been dealt with, so I am closing it.
