### ISSUE TITLE
identifiers reserved according to external standards

### ISSUE THREAD

**Issue by elfring** [Stichting-MINIX-Research-Foundation/minix#113]
I have looked at a few header files again. I see that identifiers like the following are used in the source files.
- [`_TABLE`](https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/20054ae93f6e47654fed4974be64f313fdd85de6/minix/kernel/glo.h#L4)
- [`__INTERRUPT_H__`](https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/433d6423c39e34ec4b79c950597bb2d236f886be/minix/kernel/interrupt.h#L1)

I am informed that [such a name pattern (leading underscrore and a following uppercase letter) is reserved](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797) for the use in implementations of compilers for the programming languages "C" and "C++".

I assume that a couple of header files [do not belong to C/C++ compiler implementations](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) here but to operating system implementations.
Do [any symbols need further adjustments](https://groups.google.com/d/msg/minix3/dStsdZ50eHM/95m9vriLnRAJ) to make them completely standard-compliant?

**Comment by dcvmoole** [comment]
Yes, probably. We'll look into this as soon as we've done the millions of more important things.

**Comment by dcvmoole** [comment]
We will revisit this issue if and when it results in actual conflicts. Thanks for reporting.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
