### ISSUE TITLE
pkgin up doesn't work

### ISSUE THREAD

**Issue by tps800** [Stichting-MINIX-Research-Foundation/minix#12]
Assume setup:

```
no_proxy=localhost,127.0.0.1
ftp_proxy=http://proxy.domain:8080
http_proxy=http://proxy.domain:8080
```

then

```
pkgin up
```

sitts just there, waiting for hours.
Trying

```
fetch -v ftp://ftp.minix3.org/pub/minix/packages/3.2.1/i686/All/pkg_summary.bz2
```

Just tells about timeout of the service. From linux or windows (same setup), with fetch or wget -- no problem. The file arrives within seconds.

**Comment by tps800** [comment]
Since pkgin is used from NetBSD and the version used there (0.7.0) works as expected, the one found in minix (0.6.4nb5) doesn't, I assume it is a minix problem. It might be bugs fixed upstream.

**Comment by dcvmoole** [comment]
Is this the same issue as #58 now though, or?

**Comment by tps800** [comment]
Yes. Looks like, since pkgin uses fetch to get files from servers.

**Comment by dcvmoole** [comment]
I am getting the following output on minix-current:

> 10.0.2.15# ftp_proxy=http://[proxy]:8080 fetch -v ftp://ftp.minix3.org/pub/minix/packages/3.2.1/i686/All/pkg_summary.bz2
> looking up [proxy]
> connecting to [proxy]:8080
> requesting ftp://ftp.minix3.org/pub/minix/packages/3.2.1/i686/All/pkg_summary.bz2
> fetch: ftp://ftp.minix3.org/pub/minix/packages/3.2.1/i686/All/pkg_summary.bz2: size of remote file is not known
> pkg_summary.bz2                                         48kB  107 kBps
> 10.0.2.15#

In other words, it seems to work fine here.. Could you please provide more information towards reproducing and/or narrowing down the problem, for example the fetch(1) output you get, and possibly the output of running fetch(1) through trace(1)?

**Comment by dcvmoole** [comment]
After almost two years we have still not received the input needed to continue working on this issue. Therefore I am closing it. Please feel free to reopen it with more information, though.

**Comment by tps800** [comment]
still does not work (sh)

ftp_proxy=http://proxy:8080
http_proxy=http://proxy:8080
https_proxy=http://proxy:8080
rsync_proxy=http://proxy:8080

export ftp_proxy http_proxy https_proxy rsync_proxy

fetch -v https://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/i386/7.0/All/openssh-7.6.1.tgz
looking up ftp.netbsd.org
connection to ftp.netbsd.org:443
fetch: https://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/i386/7.0/All/openssh-7.6.1.tgz: Connection refused.

The same done on NetBSD 7.0 in sh works. Thus: standard install off minix3 has a broken fetch!
