### ISSUE TITLE
Installation script is broken

### ISSUE THREAD

**Issue by boricj** [Stichting-MINIX-Research-Foundation/minix#121]
~~Pull request #120 (commit a7a79fa)~~ Commit a617090 broke the setup script. Trying to perform installation _on a 0's filled disk_ will fail at step 4 and hang the script.

~~Given the nature of the changes made, there's no obvious reason why would this break.~~ _Wasn't caused by #120_

Output of installation script on QEMU:
<pre>
 --- Substep 3.3: Confirm your choices ---------------------------------

This is the point of no return.  You have selected to install MINIX 3
into region 0 of disk /dev/c0d0.  Please confirm that you want
to use this selection to install MINIX 3.

Are you sure you want to continue?  Please enter 'yes' or 'no': yes

 --- Step 4: Reinstall choice ------------------------------------------
fs cache: I/O error on device 3/129, block 0 (0)
mfs(65576): panic: MFS: error getting block (897,0): -5
syslib:panic.c: stacktrace: 0x8058e36 0x804835c 0x804dc06 0x804d975 0x8049495 0x8051610 0x8050bf5 0x8050cc9 0x804cead 0x80481eb 0x8048118
</pre>

It is followed by this error when killing the script:
<pre>
VFS: path lookup error; root node not found
</pre>

**Comment by dcvmoole** [comment]
Could you check, eg with part(8), if your previous /home partition (i.e. /dev/c0d0p0s1 aka 3/129) actually has zero sectors assigned to it? Not that the whole system should fail on that even if so :) but it could at least explain why the driver is returning a read of zero bytes when trying to read the superblock, and possibly provide a first towards determining what created this situation in the first place..

**Comment by boricj** [comment]
The system doesn't fail, the script merely hangs and can be killed with `Ctrl-C`. Switching to another virtual terminal works too.

I'm using a freshly created QCOW2 disk image, the whole image is filled with 0's before installation and so is the partition table. I used automatic mode for partitioning. When the script hangs, here's the output for `part /dev/c0d0` :
```
  Select device       ----first----  --geom/last--  ------sectors-----
    Device             Cyl Head Sec   Cyl Head Sec      Base      Size        Kb
    /dev/c0d0                         520  128  63
                         0    0   0   520   16  15         0   4194304   2097152
Num Sort   Type
 0*  p0  81 MINIX        0    1   0   519  127  62        63   4193217   2096608
 1   p1  00 None         0    0   0     0    0  -1         0         0         0
 2   p2  00 None         0    0   0     0    0  -1         0         0         0
 3   p3  00 None         0    0   0     0    0  -1         0         0         0
```

All good. However, for `/dev/c0d0p0` :
```
  Select device       ----first----  --geom/last--  ------sectors-----
    Device             Cyl Head Sec   Cyl Head Sec      Base      Size        Kb
    /dev/c0d0p0                       520  128  63
                         0    1   0   519  127  62        63   4193217   2096608
Num Sort   Type
 0   0   00 None         0    0   0     0    0  -1         0         0         0
 1   1   00 None         0    0   0     0    0  -1         0         0         0
 2   2   00 None         0    0   0     0    0  -1         0         0         0
 3   3   00 None         0    0   0     0    0  -1         0         0         0
```

So the automatic mode hasn't partitioned `/dev/c0d0p0`... I manually partitioned like this :
```
  Select device       ----first----  --geom/last--  ------sectors-----
    Device             Cyl Head Sec   Cyl Head Sec      Base      Size        Kb
    /dev/c0d0p0                       520  128  63
                         0    1   0   519  127  62        63   4193217   2096608
Num Sort   Type
 0*  0   81 MINIX        0    1   1    49   78  13        64    400000    200000
 1   1   81 MINIX       49   78  15    99   27  27    400065    400000    200000
 2   2   81 MINIX       99   27  28   496    5   5    800065   3200000   1600000
 3   3   00 None         0    0   0     0    0  -1         0         0         0
```

After that, the setup script with automatic partitioning worked and the installed system booted.

Looks like automatic partitioning is broken on empty (0's filled) disks.

I checked with `minix_R3.4.0rc2-373b793.iso` and it doesn't exhibit this problem. My instinct told me to `git log 373b793..a7a79fa minix/commands/setup/`, one match was found : a617090dc.

Reverting this commit solved the issue, so it's a regression caused by a617090dc and not #120.

By the way, after `setup` hangs (so after `mount -t mfs /dev/c0d0p0s0` on an clean, 0's filled disk) VFS seems really confused : the `mount` command hangs, killing it will make it linger on as a zombie process until I log out from the terminal it was invoked from. `sync` exhibits the same behavior from then on too. From time to time `VFS: path lookup error; root node not found` will show up on the terminal. Should I open an issue about this ?

**Comment by dcvmoole** [comment]
Thanks for all the info! That helped and I was able to reproduce the issue here as well.

> Reverting this commit solved the issue, so it's a regression caused by a617090

Well, not exactly either: prior to a617090, preserving /home had become impossible altogether, so that commit simply made an older bug resurface. It seems that the real bug is a product of my reworking libminixfs (last summer) and MFS's subsequent new inability to cope with unreadable superblocks in particular. I'll work on a fix.

> By the way, [..] VFS seems really confused [..] Should I open an issue about this ?

Yes please. VFS not being able to fully recover from a crashed FS is a known issue that's been there for a long time, but it would be great if we could resolve that as well. Not as pressing as no longer being to perform fresh installs though..

**Comment by adieuveedu** [comment]
Hello,

i too am facing this issue, the script hangs + i am not able to partition manually either, any status update on this issue?


Thanks

**Comment by dcvmoole** [comment]
Yes, incidentally a patch is already pending and it is scheduled be fixed in minix-master within the next few days!

**Comment by adieuveedu** [comment]
Thank you really appreciate it

**Comment by dcvmoole** [comment]
Fortunately this was easy to reproduce without building a new installation image each time. As a result, I am confident that it is fixed even though I haven't tested the installation script with the fix :) If with this patch the problem hasn't entirely gone away - in terms of both functionality and aesthetics - please let me know. In any case, thanks for the report!
