### ISSUE TITLE
Minix 3.4.0 RC 2 frozen on real i386 hardware

### ISSUE THREAD

**Issue by Tookmund** [Stichting-MINIX-Research-Foundation/minix#122]
I downloaded the latest 3.4.0 disk (http://download.minix3.org/iso/snapshot/minix_R3.4.0rc2-373b793.iso.bz2) and burned the iso to a cd. 
This cd works fine in qemu, but on real hardware it freezes at

~~Root device name is /dev/c0d2~~
EDIT: Wrong line 
````
/dev/c0d2 is mounted on /
````
I powered it off and tried again with the same result
It's been sitting there for about an hour now.
I'll leave it on overnight to see what happens but I can't imagine anything will.

**Comment by Tookmund** [comment]
Ok so tested this out on a thinkpad r51  and it works fine.
This might be a hardware problem or maybe just a really slow disk drive.

**Comment by Tookmund** [comment]
Whoops. Tried again and it's actually freezing on a different step 
Edited my original comment

**Comment by dcvmoole** [comment]
Did/do earlier versions of minix work on this machine though, ie is it a regression?

**Comment by Tookmund** [comment]
3.3.0 freezes as well so I'm going to assume this is a hardware problem.
If I can find anything to the contrary I will reopen this bug.

**Comment by dcvmoole** [comment]
Alright cool. It's still a bad thing and may well be a minix bug of course, but if it's not a regression it's going to be a whole lot harder to track it down.. Thanks for checking!
