### ISSUE TITLE
virtio.c:266]: (style) 5 * Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#130]
1.

src/minix/lib/libvirtio/virtio.c:266]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Source code is

 if ((r = init_phys_queues(dev) != OK)) {

Some duplicates:

[src/minix/lib/libvirtio/virtio.c:753]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.
[src/minix/lib/libvirtio/virtio.c:761]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.
[src/minix/lib/libvirtio/virtio.c:793]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.
[src/minix/lib/libvirtio/virtio.c:801]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

**Comment by dcvmoole** [comment]
Fixed in dc2c582f364d955cff3a86092716702b099d2db2.
