### ISSUE TITLE
src/minix/commands/cawf/string.c:46]: (style) Redundant condition

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#136]
src/minix/commands/cawf/string.c:46]: (style) Redundant condition: If 'EXPR == ' '', the comparison 'EXPR' is always true.

Source code is

    while (*s && *s == ' ')

Suggest new code 

    while (*s == ' ')

**Comment by dcvmoole** [comment]
Fixed in 4d3708913c2076bda91438dab93c91e44ba5a7cf. I was really hoping github would correctly parse the issue lists in my patches, but github's parsing is letting me down for the second time. Oh well.
