### ISSUE TITLE
src/minix/lib/libsys/rmib.c:947: bad % specifier ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#141]
src/minix/lib/libsys/rmib.c:947]: (warning) %d in format string (no. 2) requires 'int' but the argument type is 'ssize_t {aka long}'.

Source code is

       printf("lsys:rmib: unable to send reply to %d: %d\n",
            m_in->m_source, r);

**Comment by dcvmoole** [comment]
Quite right! If only you were my compiler. Thanks again. I'll pick all these up ASAP!
