### ISSUE TITLE
Lua is broken

### ISSUE THREAD

**Issue by boricj** [Stichting-MINIX-Research-Foundation/minix#160]
Trying to launch `lua` results in the following error : `lua: core and library have incompatible numeric types`.

Uncommenting `LUA_32BITS` in  [external/mit/lua/dist/src/luaconf.h:43](https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/6ddb33542af04356a66b658478494d3179562f63/external/mit/lua/dist/src/luaconf.h#L43) makes Lua work again, but I don't know if this is the proper fix to make.

**Comment by PforPain** [comment]
can you try:
```
#if LUA_32BITS
#define LUA_32BITS
#endif
```
See if that works too, if it does then that is it.

**Comment by dcvmoole** [comment]
Fixed by unlocking a previously NetBSD-specific block. Thanks for reporting!
