### ISSUE TITLE
ftpd bombs on 3.4.0-RC2

### ISSUE THREAD

**Issue by antoineL** [Stichting-MINIX-Research-Foundation/minix#162]
Starting the `ftpd(8)` daemon with
> tcpd ftp /usr/libexec/ftpd &

While trying to put (upload to MINIX) a file, it stops around 120 KB with
> (srcpath)/minix/servers/vm/pagetable.c:560: assert
> "!(pt->pt_dir[pde] & ARCH_VM_BIGPAGE)" failed, function "pt_ptalloc_in_range"
> vm(8): panic: assert failed
> syslib:panic.c: stacktrace: 0x805aaa6 0x805a9b7 0x8051436 0x8050902 0x804ccda
> 0x804d677 0x804fc07 0x804f9d1 0x80484d9 0x80481eb 0x8048118

**Comment by dcvmoole** [comment]
> 219827 bytes sent in 00:00 (214.67 KiB/s)
> ftp>

I cannot reproduce this at least over localhost, is there anything else that is needed to reproduce the issue?

Also, could you please add the output of "addr2line -fe /service/vm 0x805aaa6 0x805..etc"?

**Comment by antoineL** [comment]
Fact is I cannot reproduce it today (on a cleaner environment.)

I believe this can be closed as "nonreproducible".

**Comment by dcvmoole** [comment]
Okay - of course please do reopen if you find out more. The fact that this happened even once is worrying..
