### ISSUE TITLE
How to install a new Ethernet card driver in Minix 3.4.0 and "ping" another computer?

### ISSUE THREAD

**Issue by XidianGeneral** [Stichting-MINIX-Research-Foundation/minix#166]
In my computer, the rtl8139 driver is not the default Ethernet card driver.
I have rewritten the rtl8139 driver, and then use the command to install it:
$ service up $PWD/rtl8139

and then I add the text to the file "/etc/inet.conf":
"eth1 rtl8139 0 ;"

and then I remove the inet service:
$ service down inet

and then I install the inet service:
$ service up /service/inet

but I am failed to use the "ping" command, and the failure message is:
$ ping: Cannot create socket: Device not configured

So how to install my rtl8139 driver in Minix 3.4.0 and "ping" another computer?

**Comment by dcvmoole** [comment]
You first have to configure the device by assigning an IP address to it etc. However, for questions regarding how to use MINIX3, please post on the MINIX3 google group: https://groups.google.com/group/minix3 . This issue tracker is for issues that have to be fixed in MINIX3 itself.
