### ISSUE TITLE
src/bin/ed/cbc.c: 2 * array index used before limit check ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#18]
1.

[src/bin/ed/cbc.c:306]: (style) Array index 'i' is used before limits check.

Source code is

        for (i = 0; inbuf[i] && i < 16; i++)

2.

[src/bin/ed/cbc.c:326]: (style) Array index 'i' is used before limits check.

Duplicate.

**Comment by dcvmoole** [comment]
Thank you for filing an issue. However, this code is actually from NetBSD; we just use it. Please file a bug report with NetBSD; if they make the change, we will automatically get it as part of the next sync with the NetBSD code.
