### ISSUE TITLE
Missing cache.h

### ISSUE THREAD

**Issue by blakemcbride** [Stichting-MINIX-Research-Foundation/minix#186]
Hi trying to build minix on a 64 bit Linux box.  Getting the following:

$ releasetools/x86_hdimage.sh
     .
     .
     .
 \#    create  vm/mem_anon_contig.d
CC=/home/blake/Backup/minix.git/../obj.i386/tooldir.Linux-3.13.0-37-generic-x86_64/bin/i586-elf32-minix-clang /home/blake/Backup/minix.git/../obj.i386/tooldir.Linux-3.13.0-37-generic-x86_64/bin/nbmkdep -f mem_anon_contig.d.tmp  --   -std=gnu99     --sysroot=/home/blake/Backup/minix.git/../obj.i386/destdir.i386 -I/home/blake/Backup/minix.git/minix/servers/vm -I/home/blake/Backup/minix.git/minix/servers/vm/arch/i386 -I/home/blake/Backup/minix.git/minix -D_MINIX_SYSTEM=1      /home/blake/Backup/minix.git/minix/servers/vm/mem_anon_contig.c &&  mv mem_anon_contig.d.tmp mem_anon_contig.d
\#    create  vm/mem_cache.d
CC=/home/blake/Backup/minix.git/../obj.i386/tooldir.Linux-3.13.0-37-generic-x86_64/bin/i586-elf32-minix-clang /home/blake/Backup/minix.git/../obj.i386/tooldir.Linux-3.13.0-37-generic-x86_64/bin/nbmkdep -f mem_cache.d.tmp  --   -std=gnu99     --sysroot=/home/blake/Backup/minix.git/../obj.i386/destdir.i386 -I/home/blake/Backup/minix.git/minix/servers/vm -I/home/blake/Backup/minix.git/minix/servers/vm/arch/i386 -I/home/blake/Backup/minix.git/minix -D_MINIX_SYSTEM=1      /home/blake/Backup/minix.git/minix/servers/vm/mem_cache.c &&  mv mem_cache.d.tmp mem_cache.d
/home/blake/Backup/minix.git/minix/servers/vm/mem_cache.c:26:10: fatal error: 'cache.h' file not found
#include "cache.h"
         ^
1 error generated.
nbmkdep: compile failed.
*** [mem_cache.d] Error code 1

nbmake[7]: stopped in /home/blake/Backup/minix.git/minix/servers/vm
1 error

nbmake[7]: stopped in /home/blake/Backup/minix.git/minix/servers/vm
*** [dependall-vm] Error code 2

nbmake[6]: stopped in /home/blake/Backup/minix.git/minix/servers
1 error

nbmake[6]: stopped in /home/blake/Backup/minix.git/minix/servers
*** [dependall-servers] Error code 2

nbmake[5]: stopped in /home/blake/Backup/minix.git/minix
1 error

nbmake[5]: stopped in /home/blake/Backup/minix.git/minix
*** [dependall-minix] Error code 2

nbmake[4]: stopped in /home/blake/Backup/minix.git
1 error

nbmake[4]: stopped in /home/blake/Backup/minix.git
*** [do-build] Error code 2

nbmake[3]: stopped in /home/blake/Backup/minix.git
1 error

nbmake[3]: stopped in /home/blake/Backup/minix.git
*** [build] Error code 2

nbmake[2]: stopped in /home/blake/Backup/minix.git
1 error

nbmake[2]: stopped in /home/blake/Backup/minix.git
*** [distribution] Error code 2

nbmake[1]: stopped in /home/blake/Backup/minix.git
1 error

nbmake[1]: stopped in /home/blake/Backup/minix.git
*** [release] Error code 2

nbmake: stopped in /home/blake/Backup/minix.git
1 error

nbmake: stopped in /home/blake/Backup/minix.git

ERROR: Failed to make release
*** BUILD ABORTED ***

**Comment by dcvmoole** [comment]
That shouldn't happen. Do you actually have a "cache.h" file in the minix/servers/vm/ subdirectory of your checked-out minix source tree? It most definitely should be there, as is also visible through gitweb: http://git.minix3.org/index.cgi?p=minix.git;a=tree;f=minix/servers/vm;h=1d14040e7052f7a901962676eb477d92c016b6bc;hb=HEAD

**Comment by sambuc** [comment]
This look like either you have adapted the sources, or the checkout was incomplete.

Our test infrastructure runs on Ubuntu 14.04LTS, 64bits, and passed the nightly build so far (example [nightly run of 24.11.2016](http://jenkins.minix3.org/job/precommit-vm-x86-cross/588/).

Please do the following to return to a clean state: 
```
 $ git clean -dxf .
 $ git checkout .
```

If this doesn't work can you provide us the results of ```git log -1 ``` and ``` git status```.

Can you come back to us to update the state of this issue? 

Kind regards

**Comment by blakemcbride** [comment]
I did:

rm  -rf *
git checkout --force

and now everything works.  Sorry about the trouble, and thanks for a great system!

Blake

**Comment by visde12** [comment]
Even i am observing the same issue
