### ISSUE TITLE
A problem when running "recwave" in a new sound card driver

### ISSUE THREAD

**Issue by XidianGeneral** [Stichting-MINIX-Research-Foundation/minix#189]
Hi,
I have written a new sound card driver, and I want to test it using "recwave".
I input the command in the shell:
$ mknod /dev/rec c 13 1
$ service up $PWD/newdriver -dev /dev/audio
$ recwave -b16 -s1 -r44100 my.wav

The output is:
Bits per sample   : 16
Stereo            : yes
Samples per second: 44100
Press spacebar to start sampling...
Sampling, press spacebar to stop...

But when I press spacebar for the second time, no reaction occurs ......

I want to know is there any mistake in my steps when running "recwave"?

Thanks :)

**Comment by boricj** [comment]
Here's the relevant loop in the recwave source code (https://github.com/Stichting-MINIX-Research-Foundation/minix/blob/master/minix/commands/recwave/recwave.c) :

```
  printf("Sampling, press spacebar to stop...\n");
  while(!(read(0, &c, 1) == 1 && c == ' '))
  {
    /* Read sample fragment and write to sample file */
    read(audio, buffer, fragment_size);
    write(file, buffer, fragment_size);
    data_len+= fragment_size;
  }
```

If the loop does not iterate, my guess is that your driver blocks on the read call for some reason.

**Comment by XidianGeneral** [comment]
Thanks, you are right.
I find that my driver encounters some troubles when handling interrupts ...

**Comment by dcvmoole** [comment]
Looks like there is nothing to do on our end here then :)
