### ISSUE TITLE
src/minix/commands/recwave/recwave.c:139: array index used before sanity check ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#19]
[src/minix/commands/recwave/recwave.c:139]: (style) Array index 'i' is used before limits check.

  while (argv[i][0] == '-' && i < argc)

Maybe

  while ((i < argc) && (argv[i][0] == '-'))

would be better code.

**Comment by sambuc** [comment]
Seems fair.

Please submit a pull request or a patch to the minix dev list. 

Opening issues for every one-liner change you might find with your tool will be a bit overkill. You have a clear patch proposal, no need to force someone to redo manually the same change. This is just ill-spend time and efforts.

I will be looking forward to your patch.


Best regards, 

Lionel

**Comment by dcb314** [comment]
>Please submit a pull request or a patch to the minix dev list. 

I just find problems, not fix them.

Someone more familiar with the code has better knowledge how to fix, if any.

>Opening issues for every one-liner change you might find with your tool will be a bit overkill.

Tool is http://sourceforge.net/projects/cppcheck/

*Really* useful for C and C++ code.

**Comment by sambuc** [comment]
Fair enough,

I was mistaken on your intentions, as you provided a perfectly valid solution at the same time.


Regards,

Lionel
