### ISSUE TITLE
A questionable code in audio_fw.c

### ISSUE THREAD

**Issue by Jrdevil-Wang** [Stichting-MINIX-Research-Foundation/minix#191]
Around line 606 of /minix/lib/libaudiodriver/audio_fw.c, function _handle_int_read_ is trying to copy a fragment of audio data from dma buffer to extra buffer.
I think the operation here is not complete. A line should be added as "sub_dev_ptr->BufLength += 1;".

**Comment by dcvmoole** [comment]
I agree. Fix pending.

**Comment by dcvmoole** [comment]
Thanks for the report!
