### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Palastia** [Stichting-MINIX-Research-Foundation/minix#193]
Greetings,

I get the following error when trying to rebuild from source after cloning from git:

![virtualbox_minix 3 4 0 rc2_30_12_2016_21_54_56](https://cloud.githubusercontent.com/assets/23260108/21566125/aecd36a2-ceda-11e6-8c51-9ffe71fd41ce.png)

Thanks and regards

**Comment by boricj** [comment]
The error got scrolled off-screen. Can you redirect the output of the command (both standard and error streams) into a file and attach it ? Something along the lines of `command > build.log 2>&1` should do the trick.

**Comment by sambuc** [comment]
Assuming you are starting from the latest minix iso, i.e. 3.4.0-RC2, did you follow the docs/UPDATING instructions?

Kind regards.

**Comment by Palastia** [comment]
Thank you for the assistance, I am rerunning make build after realizing I may have forgotten to install some libraries

**Comment by dcvmoole** [comment]
As mentioned in the other issue, for support questions please use the google group.
