### ISSUE TITLE
src/minix/commands/autopart/autopart.c:1534: dead code block ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#20]
[src/minix/commands/autopart/autopart.c:1534] -> [src/minix/commands/autopart/autopart.c:1535]: (warning) Opposite conditions in nested 'if' blocks lead to a dead code block.

    if ((device= open(curdev->name, mode= O_RDWR, 0666)) < 0) {
        if (device >= 0) { close(device); device= -1; }
        return;
    }

**Comment by Tookmund** [comment]
I'm working on this
https://github.com/Tookmund/minix/tree/iss20
I think I have fixed it but I will test my fix before I submit a pull request
