### ISSUE TITLE
My 3Com Ethernet card can not supported well by Minix 3c90x driver

### ISSUE THREAD

**Issue by XidianGeneral** [Stichting-MINIX-Research-Foundation/minix#201]
Hi, 
I have a 3Com Ethernet card (PCI number: 10b7:9055), and it should be supported by Minix 3c90x driver according to its configuration file (/etc/system.conf.d/3c90x).
But I find it is failed to use "dhcp", "ping" and other network applications in Minix 3.4.0.
Did anybody encounter this problem? Or this driver should be improved?

Best wishes,
Jia-Ju Bai

**Comment by dcvmoole** [comment]
Hm, that is strange. I have a card with that exact PCI ID and it worked fine for me last time I tested it, and that isn't all that long ago. I have no idea what might be going on in your case, but it's probably a bug of some sorts. Any efforts that could help track down or even solve the problem would be highly appreciated!

**Comment by XidianGeneral** [comment]
Oh, I find the failure happened because the card is not plugged tightly in the PCI slot at that time.
The 3c90x driver works well when I correctly plug the card.
Sorry for my fault :(

**Comment by dcvmoole** [comment]
Oh haha, no problem at all! I'm just glad to hear the driver is okay :)
