### ISSUE TITLE
src/sys/arch/i386/stand/lib/dosfile.c:63: missing breaks in switch ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#202]
switch (doserrno) {
        case 1:
        case 4:
        case 12:
        default:
        err = EIO;
        case 2:
        case 3:
        err = ENOENT;
        case 5:
        err = EPERM;
        case 6:
        err = EINVAL;
    }

**Comment by dcvmoole** [comment]
Hello! Thanks for the report, however I'm afraid this is NetBSD-imported code again, and so not part of what we maintain ourselves. It looks like this issue has been fixed in NetBSD-current already, so we will eventually pull in the fix that way as well.
