### ISSUE TITLE
src/sys/arch/i386/stand/lib/netif/3c90xb.c:349: poor error checking ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#204]
src/sys/arch/i386/stand/lib/netif/3c90xb.c:349]: (style) Checking if unsigned variable 'ether_medium' is less than zero.

Source code is

        ex_probemedia();
        if (ether_medium < 0)
            return 0;

but

unsigned ether_medium;

and in function ex_probe_media()

bad:
    ether_medium = -1;

Suggest new code

       if (ether_medium == (unsigned int) -1)
            return 0;

**Comment by dcvmoole** [comment]
Same here..
