### ISSUE TITLE
src/sys/dev/pci/pci_verbose.c: 2 * leap and then look if its ok ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#205]
1.

[src/sys/dev/pci/pci_verbose.c:132]: (style) Array index 'n' is used before limits check.

Source code is

        while (pci_vendors[n] != 0 && n < __arraycount(pci_vendors))
            n++;

2.

[src/sys/dev/pci/pci_verbose.c:153]: (style) Array index 'n' is used before limits check.

Duplicate.

**Comment by dcvmoole** [comment]
Hmm, neither upstream nor our copy of this file has that many lines at all: http://git.minix3.org/index.cgi?p=minix.git;a=blob;f=sys/dev/pci/pci_verbose.c;h=f3e5d8716d78d3ae2bbda6c87db9985815685ee6;hb=HEAD

Either way, same story: this is NetBSD-imported code :)
