### ISSUE TITLE
Access to minix source code

### ISSUE THREAD

**Issue by Solfath** [Stichting-MINIX-Research-Foundation/minix#218]
After installing minix3.3 in my virtualbox in window, I can not access the source code contain the src file at least, this folder is empty, so how can I get the source files?

**Comment by dcvmoole** [comment]
Hello; this issue tracker is for issues with MINIX 3 itself, not for support questions. For the latter, please use the MINIX 3 google group: https://groups.google.com/forum/#!forum/minix3 . As you will see, one of the most recent threads on there provides an answer to your question.
