### ISSUE TITLE
src/minix/commands/devmand/main.c:547: possible unlimited string read ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#22]
[src/minix/commands/devmand/main.c:547]: (warning) scanf without field width limits can crash with huge input data.

    res = fscanf(fd , "%s\n", buf);

Suggest new code

    res = fscanf(fd , "%256s\n", buf);

**Comment by dcb314** [comment]
Now get

[src/minix/commands/devmand/main.c:547]: (error) Width 256 given in format string (no. 1) is larger than destination buffer 'buf[256]', use %255s to prevent overflowing it.

Looks like an off by one error to me.

**Comment by Tookmund** [comment]
Whoops! Forgot about NULL. I'll propose a fix soon.
