### ISSUE TITLE
pkg_add: cannot install packages

### ISSUE THREAD

**Issue by rlfnb** [Stichting-MINIX-Research-Foundation/minix#223]
Installed Minix3.4 RC6 and tried to install openssh (as an example):

the pkg_add log says:

pkg_add: Warning: package 'openssh-7.3.1' was built for a platform:
pkg_add: Minix/i386 3.4.0 (pkg) vs. NetBSD/i386 3.4.0 (this host)
pkg_add: 1 package addition failed. 

A lot of more packages are impacted as well, e.g. executing pkgin_sets leads to 20 errors like the one described above.

**Comment by ultijlam** [comment]
Your system is incorrectly identifying itself as NetBSD/i386.  What does `uname -a` give on your system?

**Comment by ultijlam** [comment]
Also, you should strive to give the exact commands that produce your problem so that it can be reproduced on another system.

**Comment by rlfnb** [comment]
used an old image (rc2) by accident
