### ISSUE TITLE
getting no dhcp ip with hz=1024 since lwIP import

### ISSUE THREAD

**Issue by rlfnb** [Stichting-MINIX-Research-Foundation/minix#225]
im running minix on bare metal with a working network interface (i82573L). I observed, im getting no IP address assigned, when im changing the number of ticks per second via the hz=1024 boot parameter. I assume, there's an use of tickdelay instead of "sleep(unsigned millis)". As its a common mistake, I would suggest to introduce a "sleep" function with an absolute value in millis to prevent such a behavior?

**Comment by dcvmoole** [comment]
With #226 merged this should be resolved.
