### ISSUE TITLE
cant git clone with 128 MB RAM in qemu

### ISSUE THREAD

**Issue by rlfnb** [Stichting-MINIX-Research-Foundation/minix#227]
if you want to reproduce:

qemu-img test.img 8G
qemu-system-i386 -boot once=d -drive test.img,if=ide,format=raw -cdrom rc6.iso 
install it, reboot do a pkgin up; pkgin install git-base; cd /usr ; git clone git://git.minix3.org/minix src

minix# git clone git://git.minix3.org/minix src
Cloning into 'src'...
remote: Counting objects: 184375, done.
remote: Compressing objects: 100% (93059/93059), done.
remote: Total 184375 (delta 106843), reused 163392 (delta 86744)
Receiving objects: 100% (184375/184375), 142.43 MiB | 1.39 MiB/s, done.
Resolving deltas: 100% (106843/106843), done.
VM: vm_allocpage: alloc_mem failed48)
newslabdata: vm_allocpage failed
vfs_request: no memory for request node
VM: mappedfile_pagefault: vfs_request failed
VM: pagefault: SIGSEGV 98508 pagefault not handled
PM: coredump signal 11 for 662 / git
git       98508 0x803ac38 0x8039b04 0x81aab87 0x817d6de 0x817ce9a 0x817fd5b 0x817d7e3 0x817f094 0x81894db 0x81893f3 0x818952c 0x81114b9 0x81110be 0x819b121 0x8071e07 0x804b7c7 0x804b052 0x80d898b 0x804ae4b 0x804ad78
skipping empty region 0x7d35000-0x7d38000
anon_pagefault: out of memory
VM: map_page_region: prealloc failed
libminixfs: freeing; 1 blocks in use
libminixfs: freeing; 2241 blocks, 9179136 bytes
anon_pagefault: out of memory
VM: map_page_region: prealloc failed
libminixfs: freeing; 1 blocks in use
libminixfs: freeing; 1519 blocks, 6221824 bytes
anon_pagefault: out of memory
VM: map_page_region: prealloc failed
libminixfs: freeing; 1 blocks in use
libminixfs: freeing; 1516 blocks, 6209536 bytes
anon_pagefault: out of memory
VM: map_page_region: prealloc failed
libminixfs: freeing; 1 blocks in use
libminixfs: freeing; 1513 blocks, 6197248 bytes
anon_pagefault: out of memory
VM: map_page_region: prealloc failed
libminixfs: freeing; 1 blocks in use
libminixfs: freeing; 1510 blocks, 6184960 bytes
anon_pagefault: out of memory
VM: map_page_region: prealloc failed
libminixfs: freeing; 1 blocks in use
libminixfs: freeing; 1507 blocks, 6172672 bytes
qemu-system-i386: terminating on signal 2

**Comment by boricj** [comment]
git runs out of memory. MINIX does not have the capability to use swap, so as soon as RAM is exhausted there's not much VM can do.

Unless another operating system can clone the entire MINIX git repository with 128 MiB of RAM, no swap at all and do it with plenty of memory to spare then MINIX is not at fault here. git simply needs more memory.

**Comment by dcvmoole** [comment]
> Unless another operating system can clone the entire MINIX git repository with 128 MiB of RAM, no swap at all and do it with plenty of memory to spare then MINIX is not at fault here. git simply needs more memory.

As I mentioned on IRC as well: there are many shortcomings in the way VM deals with low-memory conditions, and my guess is that at least in theory, it might be possible for VM to unmap some of the previously faulted-in pages in order not to run out of memory in this case. However, that would be a rather involved structural change even if it would indeed alleviate git's hunger for memory.

I don't think it makes sense to track something like that by means of this issue. Seeing as the report describes expected behavior otherwise, I hope it's okay that I'm closing this issue.
