### ISSUE TITLE
src/minix/lib/libc/gen/configfile.c:537: bad call to fprintf ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#23]
[src/minix/lib/libc/gen/configfile.c:537]: (error) fprintf format string requires 2 parameters but only 0 are given.

       fprintf(stderr, "Cell at \"%s\", line %u is not a sublist\n");

**Comment by Tookmund** [comment]
I'm not sure what's supposed to be displayed here. This code is working with ````configfile_t````
which is defined as
````c
typedef struct configfile {	/* List of (included) configuration files. */
	struct configfile *next;	/* A list indeed. */
	time_t		ctime;		/* Last changed time, -1 if no file. */
	char		name[1];	/* File name. */
} configfile_t;
````

So I might be able to use name for the first format, but what should be used for the line number?

**Comment by dcvmoole** [comment]
Other, similar fprintf's use c_file and c_line, so that would be a good first option to try..
