### ISSUE TITLE
"make pkgsrc" Exits with Error code 128, "Unable to allocate memory", when RAM is actually available

### ISSUE THREAD

**Issue by martinvahi** [Stichting-MINIX-Research-Foundation/minix#231]
# Reproduction

It's a [VirtualBox](https://www.virtualbox.org/) appliance, which(~606MiB) **MIGHT** be available from 
[https://temporary.softf1.com/2017/bugs/2017_08_10_BUG_REPORT_DATA_MINIX3_v_3_3_0_make_pkgsrc_Fails.ova](https://temporary.softf1.com/2017/bugs/2017_08_10_BUG_REPORT_DATA_MINIX3_v_3_3_0_make_pkgsrc_Fails.ova)

**step_1)**
Clean install by using the
[http://download.minix3.org/iso/minix_R3.3.0-588a35b.iso.bz2](http://download.minix3.org/iso/minix_R3.3.0-588a35b.iso.bz2)

**step_2)**

    pkgin update
    
    pkgin install git-base
    pkgin install binutils
    pkgin install clang
    pkgin install bmake
    pkgin install digest
    pkgin_sets  

**step_3)**

    cd /usr
    make pkgsrc

**step_4)**
Enjoy the error message that is described at 
[https://longterm.softf1.com/2017/bugs/2017_08_10_bug_MINIX3_make_pkgsrc_Fails_t1.png](https://longterm.softf1.com/2017/bugs/2017_08_10_bug_MINIX3_make_pkgsrc_Fails_t1.png)
*([archival copy](https://archive.is/77G81))*

# Further Comments

After a restart the the ports tree at the 

    /usr/pkgsrc

seems to lack a lot of packages/ports and the 

    cd /usr
    make pkgsrc-update

fails with an error message:

    cd: can't cd to /usr/pkgsrc/minix

**Comment by sambuc** [comment]
Thank you for your report.

MINIX 3 does not have swap support, which means that if (RAM) memory runs out, processes simply fail.

The PKGSRC tree is quite big, and git complains in your log about out of memory issue. The only way to fix this problem is to provide more RAM to your appliance.

Your appliance seems to have **1613 MB** of ram dedicated, which is an odd number. I will come back to you after work and update this answer with the minimal amount of memory required for this operation.

Kind regards.

**Comment by dcvmoole** [comment]
This is a known bug in 3.3.0 that has been fixed since then (by commit 2e23f1755e14162eb3fa2237285dec556ccd360f in particular). Please upgrade to one of the 3.4.0 snapshots from http://download.minix3.org/iso/snapshot/.

**Comment by martinvahi** [comment]
Not quite. The snapshot version [lacks pkgin](https://temporary.softf1.com/2017/bugs/2017_08_11_BUG_REPORT_MINIX3_v_3_4_0_rc6_lacks_pkgin.webm).
Please correct me, if I'm wrong, but the way I as a beginner
in MINIX3 affairs understand it, the pkgin is needed for
installing the binary of the compiler, which is needed for
installing the rest of the ports/packages from source code.

This bug report should be re-opened due to the fact that 
the problem has not been solved.

**Comment by dcvmoole** [comment]
I am sorry, but you filed an issue about a specific problem in a previous release. We do not have the resources to support anything other than the current development version. The specific problem that you reported has already been solved in this development version.

If you want to use pkgin, you will have to install MINIX 3, using the "setup" command. pkgin does not work from the installation CD anymore.

**Comment by martinvahi** [comment]
I'm sorry, my mistake. I did not pay proper attention to the fact that
if the DVD-drive of the virtual appliance contains the installation CD and
the DVD-drive has a higher boot priority than the HDD of the virtual appliance, then
the instance of the MINIX3 that runs at the screen-video is the one
from the CD, not the one from the HDD of the virtual appliance.

My mistake. Sorry.

I consider the reported problem/flaw/bug solved. Thank You.

**Comment by dcvmoole** [comment]
No worries!
