### ISSUE TITLE
Out of memmory when make pkgsrc

### ISSUE THREAD

**Issue by ondratu** [Stichting-MINIX-Research-Foundation/minix#239]
Hi there,

i try to call make pkgsrc on my virtualbox instance of minix (minix_R3.3.0-588a35b.iso). And I got these message:

![virtualbox_minix_30_11_2017_12_59_23](https://user-images.githubusercontent.com/6469029/33429754-64a7d338-d5ce-11e7-8b93-ce18f1c11a14.png)

My virtualbox host have 1024MB RAM, I try it too with 2048MB RAM.

I use virtualbox on my debian buster with actual packages:
virtualbox                                5.2.2-dfsg-2
virtualbox-dkms                           5.2.2-dfsg-2
virtualbox-ext-pack                       5.2.2-2 
virtualbox-qt                             5.2.2-dfsg-2

**Comment by nikolas** [comment]
Maybe try this on minix 3.4.0-rc6.

**Comment by ondratu** [comment]
Works, fine, thanks ;-)
