### ISSUE TITLE
src/minix/lib/libddekit/src/usb_server.c:332: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#24]
[src/minix/lib/libddekit/src/usb_server.c:332]: (warning) Logical conjunction always evaluates to false: EXPR >= 256 && EXPR < 0.

        if (mx_urb->dev_id >= MAX_DEVS && mx_urb->dev_id < 0) {

**Comment by Tookmund** [comment]
I'm working on this
https://github.com/Tookmund/minix/tree/iss24
I think I have fixed it but I will test my fix before I submit a pull request
