### ISSUE TITLE
Github git clone fails 

### ISSUE THREAD

**Issue by Tookmund** [Stichting-MINIX-Research-Foundation/minix#26]
This is probably a pkgsrc bug so if I need to report it elsewhere let me know.
I am unable to checkout minix from github in minix.
It works fine with ````git.minix3.org/minix```` 

![oom official](https://cloud.githubusercontent.com/assets/2636256/6089692/dda50dec-ae34-11e4-9c7e-a01b666990ae.png)
But the github mirror fails

![oom tookmund](https://cloud.githubusercontent.com/assets/2636256/6090185/f2ccf7fc-ae3e-11e4-86a5-58cf44ec442d.png)
My fork fails as well

**Comment by ExeTwezz** [comment]
Probably you don't provide enough RAM to the virtual machine.

**Comment by Tookmund** [comment]
The machine had 5GB of disk space and 2GB of RAM as I recall

**Comment by ExeTwezz** [comment]
https://github.com/gitextensions/gitextensions/issues/1632

**Comment by Tookmund** [comment]
That worked! For anyone else with git checkout failures try adding these settings to .gitconfig (from the link above):
````
[pack]
    threads = 1
    deltaCacheSize = 128m
    packSizeLimit = 128m
    windowMemory = 128m
[core]
    packedGitLimit = 128m
    packedGitWindowSize = 128m
