### ISSUE TITLE
Error when building tools.

### ISSUE THREAD

**Issue by ExeTwezz** [Stichting-MINIX-Research-Foundation/minix#28]
Hello,
I've cloned the MINIX 3 source code using
```bash
$ git clone git://git.minix3.org/minix minixsrc
```
and want to build it. I've looked at [Developers Guide: Cross-compiling](http://wiki.minix3.org/doku.php?id=developersguide:crosscompiling#using_buildsh_directly), and run
```bash
$ sh build.sh -mi386 -O ../build tools
```
But it failed. You can read the output of the command at [GitHub Gist](https://gist.github.com/ExeTwezz/ccc1ddf426b39799bffe).
In short words, the problem is in using of `eval`, but I can't find where it is used (the line 1 is wrong):
```
checking whether /home/yuri/Документы/Books/A_Tanenbaum/OS_RIR/minixsrc/../build/tooldir.Linux-3.13.0-45-generic-x86_64/bin/nbmake sets $(MAKE)... /home/yuri/Документы/Books/A_Tanenbaum/OS_RIR/minixsrc/tools/texinfo/../../gnu/dist/texinfo/configure: 1: eval: Bad substitution
```

**Comment by sambuc** [comment]
Hello,


From your log, it seems you have **cyrillic** characters in the path containing your MINIX3 checkout:
"/home/yuri/**Документы**/Books/A_Tanenbaum/OS_RIR/minixsrc"

Can you try from a path which only contains ASCII characters and report back?


Regards, 

Lionel

**Comment by ExeTwezz** [comment]
Thanks. That helped. :+1:

**Comment by antoineL** [comment]
Le 19/02/2015 16:09, Lionel Sambuc écrivit :
> From your log, it seems you have **cyrillic** characters in the path containing your MINIX3 checkout:
> "/home/yuri/**Документы**/Books/A_Tanenbaum/OS_RIR/minixsrc"

Funny, the one program which is failing to build with Cyrillic
characters in the TOOLDIR path is... texinfo, supposedly more orientated
at foreign languages, which ought to have been spelt teχinfo but was
designed when computers were strictly English-speaking only :-)

Given the program, I guess it is not useful to report such failure to
NetBSD guys, I do not feel it will be ever considered for fixing :-(


Antoine
