### ISSUE TITLE
Cross-compiling fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by SmartPolarBear** [Stichting-MINIX-Research-Foundation/minix#288]
> /home/bear/minix/src/../obj.i386/tools/llvm-lib/libLLVMSupport/libLLVMSupport.a(Process.lo): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
Process.cpp:(.text+0xe16): undefined reference to `setupterm'
Process.cpp:(.text+0xe38): undefined reference to `tigetnum'
Process.cpp:(.text+0xe41): undefined reference to `set_curterm'
Process.cpp:(.text+0xe49): undefined reference to `del_curterm'

This is what given in the terminal.I tried several ways, including the one mentioned in a similar issue:
>I used `HOST_LDFLAGS=-ltermcap ./releasetools/x86_cdimage.sh` to build successfully

_Originally posted by @takakawa in https://github.com/Stichting-MINIX-Research-Foundation/minix/issues/229#issuecomment-383315025_

But the error still occurs

**Comment by stux2000** [comment]
You might be missing a package requirement.  I know this is an old issue but if you're still interested in trying please provide your OS version information and a link to any instructions that you're trying to follow.

**Comment by SmartPolarBear** [comment]
> You might be missing a package requirement. I know this is an old issue but if you're still interested in trying please provide your OS version information and a link to any instructions that you're trying to follow.

I could vaguely recall that at that time I finally worked around this issue by downgrading my toolchain. I am very sorry that I am not able to provide further information because it's too long ago from now.

**Comment by stux2000** [comment]
No problem, this was kind of a longshot since it's been a while since the issue was posted.  

Downgrading the toolchain makes sense: there's been reports of Minix not being able to compile properly in newer OSes which I'm sure have newer toolchains but still compiles without issue in older OSes. 

Please consider closing this issue if you deem it resolved.  Thank you and thanks for responding after all this time!
