### ISSUE TITLE
Iso image, USB image error

### ISSUE THREAD

**Issue by Phrunsys** [Stichting-MINIX-Research-Foundation/minix#332]
How do I create an iso or USB image from Minix 3.2.1

**Comment by dcvmoole** [comment]
Hello; this issue tracker is for issues with MINIX 3 itself, not for support questions. For the latter, please use the MINIX 3 google group: https://groups.google.com/forum/#!forum/minix3 . Furthermore, issues are meant to help move MINIX 3 forward. As such, issues related only to outdated MINIX 3 versions will typically be closed or ignored. If you have an actual, specific issue that you believe is a bug, please first see if you can reproduce it on MINIX 3.4.0-rc6 (currently the latest available MINIX 3 version). If so, please report it here. For issues that apply only to older versions, I'm afraid you are on your own.
