### ISSUE TITLE
fatal: unable to checkout working tree

### ISSUE THREAD

**Issue by mablinov** [Stichting-MINIX-Research-Foundation/minix#335]
Hi all,

I was curious about Minix and tried cloning the tree on my Windows 10 machine. I got the following error:

```bash
Maxim@VISHERA MINGW64 ~/prj/minix
$ git clone https://github.com/Stichting-MINIX-Research-Foundation/minix.git
Cloning into 'minix'...
remote: Enumerating objects: 184788, done.
remote: Total 184788 (delta 0), reused 0 (delta 0), pack-reused 184788
Receiving objects: 100% (184788/184788), 180.37 MiB | 7.36 MiB/s, done.
Resolving deltas: 100% (92452/92452), done.
error: invalid path 'external/bsd/bind/dist/contrib/zkt-1.1.3/examples/flat/dyn.example.net/zktlog-dyn.example.net.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Git version:
```
$ git --version
git version 2.36.0.windows.1
```

Any ideas?

Edit: I've just tried to git clone from the official website with `$ git clone git://git.minix3.org/minix` and got the same problem.

**Comment by petershh** [comment]
Hello,

Seems like NTFS does not like this path. I tried disabling
core.protectNTFS git parameter, but got some other errors.

All in all, I recommend you using Unix system if you want to work with
(or compile) Minix source code.
