### ISSUE TITLE
Compiling 'binstall/xinstall.lo' issue

### ISSUE THREAD

**Issue by nazebzurati** [Stichting-MINIX-Research-Foundation/minix#336]
Step to reproduce:
- Clone the repo main branch
- Apply `patch.txt`
- Run `./releasetools/x86_cdimage.sh`

Machine:
- OS: Ubuntu 22.04.1 LTS on Windows 10 x86_64 
- Kernel: 5.15.68.1-microsoft-standard-WSL2 
- Shell: bash 5.1.16 
- CPU: AMD Ryzen 5 3400G (8) @ 3.699GHz

Notes:
- `./glass` is the my Minix working folder name.

Attachments:
- [log.txt](https://github.com/Stichting-MINIX-Research-Foundation/minix/files/10001402/log.txt)
- [patch.txt](https://github.com/Stichting-MINIX-Research-Foundation/minix/files/10001408/patch.txt)

**Comment by nazebzurati** [comment]
I believe that this is due to repo's `./sys/sys/stat.h` is not used when cross compiling and build platform's `sys/stat.h` was used instead. 

```
...
xinstall.o: /usr/include/x86_64-linux-gnu/sys/stat.h
...
```

As attached is the `./../tools/binstall/xinstall.d` file produced when cross compiling: [xinstall.d](https://github.com/Stichting-MINIX-Research-Foundation/minix/files/10001511/xinstall.d.txt)

**Comment by petershh** [comment]
first of all, there's nbsed build failure. Are there any error message. You may want to redirect stderr to log as well.

**Comment by nazebzurati** [comment]
The `log.txt` I attached get from command `./releasetools/x86_cdimage.sh 2>&1 | tee log.txt`. Please suggest the suitable command as I believe `2>&1` have already include both stdout and stderr.

**Comment by petershh** [comment]
I've installed fresh Ubuntu 22.04.01 in WSL, cloned minix repository and appliet patch suite from #322 . Build seems like to work.

**Comment by nazebzurati** [comment]
The mentioned issue was fixed.

The steps are as follows:
1. Clone the repo or git hard reset and clean.
2. Download [#322](https://github.com/Stichting-MINIX-Research-Foundation/minix/pull/322) patch:
   `curl https://github.com/petershh/minix/commit/75e1abafd68c2eb6ded0d311facd918a7e0b8517.patch -o patch.txt`
3. Apply patch:
   `git apply --ignore-space-change --ignore-whitespace patch.txt`
4. Add string header as per [this patch](https://gist.github.com/petershh/1973b8f723fb36242c9558a23408d469) manually.
5. Run `x86_cdimage.sh` script and redirect the output to log:
   `./releasetools/x86_cdimage.sh 2>&1 | tee log.txt`
6. Let it compile!

If any of these steps is not expected, please let me know. Else, I'll close this issue soon.
Thanks for your verification and assistant!
