### ISSUE TITLE
Crash with IntelPRO/1000 MT Desktop Adapter type (8254OEM) - Oracle Virtual Box

### ISSUE THREAD

**Issue by mk1nz** [Stichting-MINIX-Research-Foundation/minix#350]
During automatic installation, Minix correctly detects the network adapter, but crashes after reboot.

![image](https://github.com/Stichting-MINIX-Research-Foundation/minix/assets/35996377/9a31513d-99fd-41db-b115-9ee93409cd90)

![image](https://github.com/Stichting-MINIX-Research-Foundation/minix/assets/35996377/4444ec16-5e2f-4170-8f27-27ecfd5eac3b)

Works with PCnet-Fast III (Am73C973)

**Comment by petershh** [comment]
Hello,

Please also attach VBox log, which is mentioned in guru mediation dialog.

I suspect triple fault, but let's confirm that.

**Comment by mk1nz** [comment]
[VBox.log](https://github.com/Stichting-MINIX-Research-Foundation/minix/files/13489245/VBox.log)

Please find attached file

**Comment by the-grue** [comment]
Any chance you could also share your .vbox configuration file?  Minix tends to be a bit picky about some of the settings, especially under the system tab.

**Comment by the-grue** [comment]
Never mind.  See closed issue #17 
Looks like a one line code fix.

**Comment by the-grue** [comment]
Hi @mk1nz I'm attaching a patched version of the e1000 service.  I did the following to get it working:

take a snapshot
copy the file to your vm (I temporarily set the network driver to PCnet-FAST III)
extract the file and validate the cksum in the image below
copy the executable to /service/e1000, this will clobber the bad service.
run the netconf command and change your network adapter to the Intel PRO/1000, set dhcp, etc.
once that is completed, shutdown the  vm and close the window
change your network adapter to Intel PRO/1000 MT
start the vm and it should now be working with your GB ethernet.

![image](https://github.com/Stichting-MINIX-Research-Foundation/minix/assets/3101080/0258c9f3-b396-45e4-8bae-04d5953c6fbb)

[e1000.gz](https://github.com/Stichting-MINIX-Research-Foundation/minix/files/13508272/e1000.gz)

**Comment by mk1nz** [comment]
Hello @the-grue ! Thank you so much. Works perfectly.
