### ISSUE TITLE
/usr/man/man1x not in man's search path

### ISSUE THREAD

**Issue by tcort** [Stichting-MINIX-Research-Foundation/minix#44]
Some older Minix-specific man pages are in `/usr/man/man1x` which `man` currently ignores.

Typing `man kermit` or `man mined` gives a not found error, even though the man pages exist in `/usr/man/man1x`.

There are a couple of possible solutions to this:

* add references to `man1x` to `/etc/man.conf`
* move the 4 man pages from `man1x` to `man1`

I'm happy to work on a fix for this when there is a consensus on the preferred solution.

**Comment by dcvmoole** [comment]
Hmm. awk.1x is for a version of awk we no longer have, kermit seems gone altogether, I highly doubt the macros thing will be useful for anyone anymore, so it looks like it's really just about mined.. I'd just move that one and delete the rest.

**Comment by antoineL** [comment]
Le 23/03/2015 11:28, David van Moolenbroek a écrit :
> Hmm. awk.1x is for a version of awk we no longer have, kermit seems
> gone altogether, I highly doubt the macros thing will be useful for
> anyone anymore, so it looks like it's really just about mined.. I'd
> just move that one and delete the rest.

It used to be an elvis(1x) page there too, I guess it was deleted with
the rest of elvis (based on name correspondence.)

I agree the correct solution is to keep mined.1 and delete the rest.
Note that mined.1x as it stands cannot be properly displayed with mandoc
(at the very least, it is lacking its "mnx.mac" macros which is a
cawf-only thing), which is I guess the reason why 1x pages were dropped
at some point from MANPATH (and adding cawf to etc/man.conf just for
mined.1x does not make too much sense).

man9/macros.9 is a copy of macros.1x and should follow it to the bin.

**Comment by sambuc** [comment]
Hey @tcort!

Good to hear from you again!

Deleting old, irrelevent manpage is fine for me.

If we are moving mined.1x, I would suggest to move it to commands/mined/ directly, as this is the NetBSD way of doing things, also makes it simpler to keep track of the documentation.
