### ISSUE TITLE
Unable to crossbuild minix via x86_hdimage.sh

### ISSUE THREAD

**Issue by Tookmund** [Stichting-MINIX-Research-Foundation/minix#48]
I checked out minix today on a new computer and attempted to crossbuild it. This failed.
The build log is posted at http://dpaste.com/18QPADC

**Comment by sambuc** [comment]
Hello Jacob,


Do you have curl installed on that computer?

It is part of the cross-compilation requirements.

After installing it, do a 
 $ git clean -dxf .
in the source minix tree, before re-running the script.


Regards, 

Lionel

**Comment by Tookmund** [comment]
Nope didn't have curl!
What else is required?

**Comment by Tookmund** [comment]
It's working now so I'm closing this issue.
curl, gcc, and make are the build requirements of x86_hdimage.sh as far as I can tell
