### ISSUE TITLE
"git clone http://git.mini3.org/minix.git src" -> Cloning into 'src'... fatal: Unable to find remote helper for 'http'

### ISSUE THREAD

**Issue by tps800** [Stichting-MINIX-Research-Foundation/minix#57]
Looks like git was compiled without http[s]-support. In tune git is unusable if you are behind a restrictive firewall bound to use a proxy to access the internet.

**Comment by tps800** [comment]
find / -name 'git-remote*'
/usr/pkg/libexec/git-core/git-remote
/usr/pkg/libexec/git-core/git-remote-ext
/usr/pkg/libexec/git-core/git-remote-fd
/usr/pkg/libexec/git-core/git-remote-testsvn

Helpers for http, https, ftp, ftps, sftp are not build and installed! Did you ever think of people living behind firewalls? This pkg needs an upgrade!

**Comment by dcvmoole** [comment]
This issue has been resolved quite a while ago now. Note that git.minix3.org does not support retrieval over http.
