### ISSUE TITLE
openntpd bails out with error "cant drop privileges: operation not permitted"

### ISSUE THREAD

**Issue by tps800** [Stichting-MINIX-Research-Foundation/minix#61]
Install openntpd, then start it:
```shell
# sh /usr/pkg/etc/rc.d/openntpd start
```

afterwards I'd awaited to find ntpd running:
```shell
# ps ax | grep ntpd
#
```

But it is not. In /var/log/messages:
```log
Jan  5 05:53:45 mx4-64 1 2015-01-05T05:53:45.150000+01:00 - ntpd 462 - - fatal:
can't drop privileges: Operation not permitted
Jan  5 05:53:45 mx4-64 1 2015-01-05T05:53:45.150000+01:00 mx4-64 ntpd 461 - -
Lost child: child exited
Jan  5 05:53:45 mx4-64 1 2015-01-05T05:53:45.150000+01:00 mx4-64 ntpd 461 - -
Terminating
```

**Comment by dcvmoole** [comment]
This has now been confirmed to be an issue with the package rather than with MINIX3 itself. The newer, pkgsrc-current version of openntpd does not even compile anymore, so I'm closing this issue for now. Please do feel free to reopen it whenever it becomes relevant again.
