### ISSUE TITLE
wget compiled without https/proxy support?

### ISSUE THREAD

**Issue by tps800** [Stichting-MINIX-Research-Foundation/minix#66]
```
--2015-04-26 12:58:33--  (try:20)  https://github.com/Stichting-MINIX-Research-Foundation/pkgsrc-ng/archive/3.3.0.zip
libidn: warning: libiconv not installed, cannot convert data to UTF-8
Connecting to proxy-lb-muc.bfs.de (proxy-lb-muc.bfs.de)|10.169.16.3|:8080... connected.
Failed reading proxy response: Function not implemented
Giving up.
```

```
# wget -V
GNU Wget 1.15 built on minix.

+digest +https -ipv6 +iri +large-file +nls +ntlm +opie +ssl/openssl

Wgetrc:
    /usr/pkg/etc/wgetrc (system)
Locale:
    /usr/pkg/share/locale
Compile:
    cc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/usr/pkg/etc/wgetrc"
    -DLOCALEDIR="/usr/pkg/share/locale" -I. -I../lib -I../lib
    -I/usr/pkg/include -I/usr/include -O2 -march=i586
    -I/usr/pkg/include -I/usr/include
Link:
    cc -O2 -march=i586 -I/usr/pkg/include -I/usr/include -L/usr/pkg/lib
    -Wl,-R/usr/pkg/lib -L/usr/lib -Wl,-R/usr/lib
    /usr/pkg/lib/libintl.so /usr/lib/libc.so -Wl,-rpath
    -Wl,/usr/pkg/lib /usr/pkg/lib/libssl.so /usr/pkg/lib/libcrypto.so
    -Wl,-rpath -Wl,/usr/pkg/lib -lz -lidn ftp-opie.o openssl.o
    http-ntlm.o ../lib/libgnu.a

Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
```

wget does not work together with proxys. Maybe it is the same issue with other parts of the system not working with proxys as expected.

**Comment by tcort** [comment]
I looked into this today, testing wget 1.17.1 (from source) and wget 1.16.3 (from pkgsrc) on Minix 3.4.0 RC2.

`https` support works. Though, for the best end user experience, you'll likely want to install `mozilla-rootcerts` too.

Proxy support doesn't work. The code that implements proxy support does a peek: `recv(fd, buf, bufsize, MSG_PEEK)`. Minix's `inet` server doesn't support this, so it returns `Function not implemented`. I tried `lwip` but I can't receive a response from my proxy server when I connect through `lwip` (even when I telnet to it... it connects, I type in my request, but I never get a response).

Side note: I tested `curl` as well and it works through my http/https proxy which is running tinyproxy. I just had to set the `http_proxy` and `https_proxy` environment variables in Minix to the proxy URL.

**Comment by dcvmoole** [comment]
While I do not have a concrete way to test this, based on @tcort's analysis, I think it is safe to say that the core of the issue has now been resolved in minix-current: the new network stack fully supports MSG_PEEK. Of course, please feel free to reopen if any issues persist on minix-current after all.
