### ISSUE TITLE
Unable to find rt_auxhelper.cc

### ISSUE THREAD

**Issue by Tookmund** [Stichting-MINIX-Research-Foundation/minix#77]
When going through an error log from a build of minix I noticed this line:
````
rt_auxhelper.cc:43:1: warning: function '__cxa_bad_cast' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
````
I cannot seem to find this ````rt_auxhelper.cc```` file. Any idea where it would be?

**Comment by boricj** [comment]
Found it :
```
boricj@boricj-debian:~/Documents/Projets/minix/src$ find . -name rt_auxhelper.cc
boricj@boricj-debian:~/Documents/Projets/minix/src$ find ../obj.i386/ -name rt_auxhelper.cc
../obj.i386/external/bsd/libc++/lib/rt_auxhelper.cc
boricj@boricj-debian:~/Documents/Projets/minix/src$
```
It's probably a byproduct of building libc++.

As for fixing it, since it's not Minix-owned code the preferred option is to fix the code upstream (and wait for the next NetBSD source code merge), to keep the difference between the two code bases as small as possible.

**Comment by Tookmund** [comment]
Ah should have thought to check there. Thx. I'll just fix minix warnings for now and work on those later. 

Jacob
