### ISSUE TITLE
Delivering messages hangs

### ISSUE THREAD

**Issue by rlfnb** [Stichting-MINIX-Research-Foundation/minix#82]
Our service sends a couple of messages in a sequence to another service via asyncsend3. The other service receives the first message only, the remaining subsequent messages are not delivered until the the sender creates a new message to the same receiver.

I assume, there's problem with sending more than one message per time slice assigned from scheduler. As a workaround, I put a tickdelay(1) in between of sending messages, which solves the problem.

**Comment by dcvmoole** [comment]
Based on your description I created a minimal test case with a client service asynsend3'ing a bunch of message to a server service, but this test case works as expected - the server receives all messages instantly. It is also worth noting that in particular communication from PM to VFS uses the pattern you are describing, and we have so far not had unexpected hangs or other problems there. It is likely that there is more to the problem..

**Comment by dcvmoole** [comment]
After well over a year we have still not received the input needed to continue working on this issue. Therefore I am closing it. Please feel free to reopen it with more information, though.
