### ISSUE TITLE
commands/isoread/isoread.c:414: Redundant condition ?

### ISSUE THREAD

**Issue by dcb314** [Stichting-MINIX-Research-Foundation/minix#83]
[src/minix/commands/isoread/isoread.c:414]: (style) Redundant condition: !Read_Dir. 'A && (!A || B)' is equivalent to 'A || B'

       if (iso_cmp(name, dir_ptr,
            (Read_Dir || (!Read_Dir && !last_in_path))) == 0)

Maybe better code

       if (iso_cmp(name, dir_ptr,
            (Read_Dir || !last_in_path)) == 0)

**Comment by boricj** [comment]
isoread is a legacy utility long overdue for retirement (see issue #13). It's been obsoleted by my rewrite of isofs, and even more so with the impending use-as-root-filesystem improvements in pull requests #76 and #63.

I expect it to be killed for good shortly after those pull requests are merged.

**Comment by dcvmoole** [comment]
Well, that's not entirely true: mounting an isofs file system requires root privileges, whereas isoread requires no special privileges, and thus, isofs does not fully obsolete isoread. I would like to know if NetBSD has anything that we can use to replace isoread altogether though, because I too don't feel like maintaining this.. :)

**Comment by boricj** [comment]
Rump? :-)

More seriously, I wonder if it's possible to create a small utility that spawns a file server, performs whatever is requested by the user, then shut it down, independently of VFS? We could replace isoread by something much more generic, not prone (so easily) to bitrot and of educational value.

Modifications to libfsdriver seems trivial to do, and a loopback device would take care of libbdev.

**Comment by dcvmoole** [comment]
Interesting ideas, but not short-term ones.. For the moment this issue is still valid..
