### ISSUE TITLE
Crashes on boot in VirtualBox / FreeBSD

### ISSUE THREAD

**Issue by yonas** [Stichting-MINIX-Research-Foundation/minix#97]
I was able to install Minix 3 in Virtualbox 4.3.32 on FreeBSD 10.2, but it crashes when it boots off the (virtual) drive.

The last line printed to screen is 
```

Starting services: random e1000 inete1000#0: Intel PRO/1000 MT Desktop Adapter (8086/100e/00) at 0.3.0
  pty
```

**Comment by yonas** [comment]
Virtualbox logs: https://gist.github.com/yonas/03988b274bfab88d637f

**Comment by dcvmoole** [comment]
Thank you for your bug report! This e1000 driver bug has already been fixed in a post-3.3.0 patch (92293fafd3877cfbb7bde350a225b2e07e737de1). For the 3.3.0 release, you could select another network interface card, for example PCnet-PCI II, in the advanced network settings of your MINIX3 VM.

**Comment by yonas** [comment]
Thanks, that worked!

**Comment by dcvmoole** [comment]
No problem; glad to hear :)

**Comment by 15w34r0n3D4y** [comment]
I download Minix 3.3.0 (stable version) but still got this error, can u update ISO file. Thank you!
